### ISSUE TITLE
model.get('_session.user') is undefined

### ISSUE THREAD

**Issue by icaliman** [derbyparty/derby-login#3]
I have this route:

``` coffee
app.get '/', (page, model, params, next) ->
  user = model.get '_session.user'
  # ...
```

When page is rendered on the client side `user` is undefined.

@vmakhaev can you help me with this issue?

**Comment by mattbrun** [comment]
Just for the records, if you use the `derby-router` package the new way to achieve this is using a route module as explained [here](https://github.com/derbyparty/derby-router#router-modules).
Cheers
