### ISSUE TITLE
[question] custom redirect urls

### ISSUE THREAD

**Issue by rasteiner** [derbyparty/derby-login#31]
Is it possible to define custom redirect urls after having logged in with a provider? 

Example: To login, now I send the user to "/auth/facebook". After they have logged in I'd like to send them to different locations based on the situation. 
I can't simply define a session variable before they reach /auth/facebook, and then read it after login, because the login process changes the session id (and therefore the session is lost after login).

Ideally I could define a redirect url by sending the users to "/auth/facebook?redirect=%2Fmy-fancy-redirect" and derby-login would handle it for me.

**Comment by zag2art** [comment]
Just try your `"/auth/facebook?redirect=%2Fmy-fancy-redirect"`. It should work exactly your way.

**Comment by rasteiner** [comment]
Oh didn't see that, thanks
